services:
  - type: worker
    name: telegram-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python milkshake.py
    envVars:
      - key: PORT
        value: 10000
